language: go
go:
- 1.x

before_install:
- wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
- sudo dpkg -i /tmp/hugo.deb

before_script:
- git clone https://${GH_TOKEN}@github.com/digital-land/digital-land.github.io.git
  public

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
