baseURL = "https://digital-land.github.io/"
languageCode = "en-uk"
title = "Digital Land"
theme = "govuk"
googleAnalytics = "UA-127566551-1"
enableRobotsTXT = true

staticDir = ["static", "src/govuk_template/assets", "src/govuk_elements/assets"]

[params]
  global_header_text = "GOV.UK"
  servicename = "Digital Land"
  users = ["Data Maintainer", "Data Modeller", "Policy Maker", "PropTech"]

  # Nav links in the side bar
  [[params.propositionlinks]]
  name = "About us"
  url = "/about"
  currentpage = true

  [[params.propositionlinks]]
  name = "Projects"
  url = "/project/"

  [[params.propositionlinks]]
  name = "Guidance"
  url = "/guidance/"

  [[params.propositionlinks]]
  name = "Users"
  url = "/users/"

  [[params.propositionlinks]]
  name = "Glossary"
  url = "/glossary/"

  [[params.propositionlinks]]
  name = "Weeknotes"
  url = "/weeknote/"

  [[params.propositionlinks]]
  name = "Blog"
  url = "/blog-post/"

  [[params.footer_meta_links]]
  name = "Cookies"
  url = "/cookies"


[taxonomies]
  tag = "tags"
  pattern = "patterns"
